create table timeline_experiences (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  year text not null,
  title text not null,
  company text not null,
  description text not null,
  icon_type text not null
);

-- Add some sample data
INSERT INTO timeline_experiences (year, title, company, description, icon_type) VALUES
('2021 - Present', 'Developer', 'Tata Technologies Ltd', 'Currently working as a Developer at Tata Technologies Ltd, contributing to various development projects.', 'code'),
('2021', 'DevOps Engineer', 'Nestorbird Ltd', 'Worked as a DevOps Engineer, implementing and maintaining CI/CD pipelines and cloud infrastructure.', 'briefcase'),
('2019 - 2021', 'Full Stack Developer Intern', 'CRTD Technologies', 'Started career as a Full Stack Developer Intern, working on various web development projects.', 'calendar');