name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Change to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use your application's Node.js version

    - name: Install Dependencies
      run: npm ci

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.HOST_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/habibur-rahman
          git pull
          npm install
          nohup npm run dev > app.log 2>&1 &
